export declare const SocketEvents: {
    readonly CONNECT: "connect";
    readonly DISCONNECT: "disconnect";
    readonly ERROR: "error";
    readonly DRIVER_LOCATION_UPDATE: "driver:location_update";
    readonly DRIVER_LOCATION_BROADCAST: "driver:location_broadcast";
    readonly DRIVER_ONLINE: "driver:online";
    readonly DRIVER_OFFLINE: "driver:offline";
    readonly RIDE_REQUESTED: "ride:requested";
    readonly RIDE_MATCHED: "ride:matched";
    readonly RIDE_CONFIRMED: "ride:confirmed";
    readonly RIDE_STARTED: "ride:started";
    readonly RIDE_COMPLETED: "ride:completed";
    readonly RIDE_CANCELLED: "ride:cancelled";
    readonly RIDE_REROUTED: "ride:rerouted";
    readonly RIDE_ETA_UPDATE: "ride:eta_update";
    readonly BOOKING_CREATED: "booking:created";
    readonly BOOKING_CONFIRMED: "booking:confirmed";
    readonly BOOKING_PICKUP: "booking:pickup";
    readonly BOOKING_DROPOFF: "booking:dropoff";
    readonly BOOKING_CANCELLED: "booking:cancelled";
    readonly CHAT_MESSAGE: "chat:message";
    readonly CHAT_TYPING: "chat:typing";
    readonly SOS_ALERT: "sos:alert";
    readonly SOS_RESOLVED: "sos:resolved";
    readonly NOTIFICATION: "notification";
    readonly JOIN_RIDE_ROOM: "room:join_ride";
    readonly LEAVE_RIDE_ROOM: "room:leave_ride";
};
export declare const ApiRoutes: {
    readonly AUTH_LOGIN: "/api/auth/login";
    readonly AUTH_REGISTER: "/api/auth/register";
    readonly AUTH_LOGOUT: "/api/auth/logout";
    readonly AUTH_REFRESH: "/api/auth/refresh";
    readonly AUTH_ME: "/api/auth/me";
    readonly USERS: "/api/users";
    readonly USER_BY_ID: "/api/users/:id";
    readonly USER_PROFILE: "/api/users/profile";
    readonly USER_ECO_STATS: "/api/users/:id/eco-stats";
    readonly USER_EMERGENCY_CONTACTS: "/api/users/emergency-contacts";
    readonly VEHICLES: "/api/vehicles";
    readonly VEHICLE_BY_ID: "/api/vehicles/:id";
    readonly RIDE_REQUESTS: "/api/ride-requests";
    readonly RIDE_REQUEST_BY_ID: "/api/ride-requests/:id";
    readonly RIDE_REQUEST_MATCHES: "/api/ride-requests/:id/matches";
    readonly RIDE_REQUEST_CANCEL: "/api/ride-requests/:id/cancel";
    readonly RIDES: "/api/rides";
    readonly RIDE_BY_ID: "/api/rides/:id";
    readonly RIDE_SEARCH: "/api/rides/search";
    readonly RIDE_CLUSTERS: "/api/rides/clusters";
    readonly BOOKINGS: "/api/bookings";
    readonly BOOKING_BY_ID: "/api/bookings/:id";
    readonly BOOKING_RATE: "/api/bookings/:id/rate";
    readonly CARBON_ESTIMATE: "/api/carbon/estimate";
    readonly CARBON_DASHBOARD: "/api/carbon/dashboard";
    readonly CARBON_LEADERBOARD: "/api/carbon/leaderboard";
    readonly DEMAND_HEATMAP: "/api/demand/heatmap";
    readonly DEMAND_PREDICT: "/api/demand/predict";
    readonly DEMAND_SURGE: "/api/demand/surge";
    readonly ROUTING_DIRECTIONS: "/api/routing/directions";
    readonly ROUTING_GREEN: "/api/routing/green";
    readonly ROUTING_TRAFFIC: "/api/routing/traffic";
    readonly SOS_ALERT: "/api/sos/alert";
    readonly SOS_RESOLVE: "/api/sos/:id/resolve";
};
export declare const ErrorCodes: {
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly INVALID_TOKEN: "INVALID_TOKEN";
    readonly TOKEN_EXPIRED: "TOKEN_EXPIRED";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly INVALID_INPUT: "INVALID_INPUT";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly ALREADY_EXISTS: "ALREADY_EXISTS";
    readonly CONFLICT: "CONFLICT";
    readonly RIDE_NOT_AVAILABLE: "RIDE_NOT_AVAILABLE";
    readonly RIDE_ALREADY_BOOKED: "RIDE_ALREADY_BOOKED";
    readonly RIDE_CANCELLED: "RIDE_CANCELLED";
    readonly NO_MATCHING_RIDES: "NO_MATCHING_RIDES";
    readonly BOOKING_CONFLICT: "BOOKING_CONFLICT";
    readonly INVALID_TIME_RANGE: "INVALID_TIME_RANGE";
    readonly TIME_WINDOW_OVERLAP: "TIME_WINDOW_OVERLAP";
    readonly TIME_WINDOW_EXPIRED: "TIME_WINDOW_EXPIRED";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE";
    readonly DATABASE_ERROR: "DATABASE_ERROR";
};
export declare const RideStatusFlow: {
    readonly pending: readonly ["matched", "cancelled"];
    readonly matched: readonly ["confirmed", "cancelled"];
    readonly confirmed: readonly ["driver_en_route", "cancelled"];
    readonly driver_en_route: readonly ["pickup_arrived", "cancelled"];
    readonly pickup_arrived: readonly ["in_progress", "cancelled"];
    readonly in_progress: readonly ["completed", "cancelled"];
    readonly completed: readonly [];
    readonly cancelled: readonly [];
};
export declare const Config: {
    readonly CLUSTER_RADIUS_KM: 1;
    readonly MIN_CLUSTER_SIZE: 2;
    readonly MAX_CLUSTER_SIZE: 4;
    readonly MAX_PICKUP_WINDOW_HOURS: 4;
    readonly DEFAULT_PICKUP_WINDOW_MINUTES: 30;
    readonly MAX_DETOUR_MINUTES: 15;
    readonly BASE_FARE: 2.5;
    readonly PRICE_PER_KM: 1.2;
    readonly PRICE_PER_MINUTE: 0.15;
    readonly MIN_SURGE_MULTIPLIER: 1;
    readonly MAX_SURGE_MULTIPLIER: 3;
    readonly POOLED_DISCOUNT_PERCENTAGE: 30;
    readonly AVG_CO2_PER_KM_GRAMS: 150;
    readonly ELECTRIC_CO2_PER_KM: 0;
    readonly MAX_PICKUP_DISTANCE_KM: 5;
    readonly MIN_MATCH_SCORE: 60;
    readonly LOCATION_UPDATE_INTERVAL_MS: 5000;
    readonly ETA_REFRESH_INTERVAL_MS: 30000;
    readonly ROUTE_DEVIATION_THRESHOLD_METERS: 200;
    readonly DEFAULT_PAGE_SIZE: 20;
    readonly MAX_PAGE_SIZE: 100;
};
//# sourceMappingURL=index.d.ts.map